### ISSUE TITLE
Latest upstream update never built

### ISSUE THREAD

**Issue by hfiguiere** [flathub/de.akaflieg_freiburg.enroute#4] opened 2022-05-05 03:23 UTC
The latest upstream update pushed to master never built.

See https://flathub.org/builds/#/builders/48/builds/10101

**Comment by kebekus** [comment] 2022-05-07 09:31
@hfiguiere Thanks for your report. I am experiencing an issue with the 'lconvert' binary that is contained in the SDK package. Starting a few months ago, the program 'lconvert' exposes a known issue that makes it always fail. According to the Qt company, the issue is fixed in current versions of Qt. I am hoping that the SDK package will include a bugfix soon so that my program compiles again.

**Comment by hfiguiere** [comment] 2022-05-07 14:49
@aleixpol any idea?

**Comment by kebekus** [comment] 2022-05-08 13:44
PS: The problem is described here: https://bugreports.qt.io/browse/QTBUG-91558

**Comment by aleixpol** [comment] 2022-05-12 00:36
I cannot see the build logs anymore.

I trust it's possible that it's a bug in Qt, if that's the case it will need fixing. If you see it gets addressed upstream tell us and we'll backport the change into our patch collection and thus org.kde.Sdk

**Comment by kebekus** [comment] 2022-05-12 06:55
@aleixpol Will do.

**Comment by kebekus** [comment] 2022-06-25 11:47
The problem has been fixed in org.kde.Sdk, the build problem is gone.

Thanks for all your help!

**Closed by kebekus** 2022-06-25 11:47 UTC
